services:
    aurelienazerty.spreadfirefox.listener:
        class: aurelienazerty\spreadfirefox\event\main_listener
        arguments:
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
